name: Deploy to S3

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Confirm AWS CLI version
      run: aws --version


    - name: Sync to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  
      run: |
        aws s3 sync ./deploy/ s3://metrolive.ctomic.com --delete

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
        --paths "/*"
